name: ci

on:
  push:
    branches:
      - "main"

env:
  NIFI_VERSION: 1.15.3

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apache nifi
        uses: actions/checkout@v2
        with:
          repository: apache/nifi
          ref: refs/tags/rel/nifi-${{ env.NIFI_VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./nifi-docker/dockerhub
          file: ./nifi-docker/dockerhub/Dockerfile
          push: true
          build-args: |
            "UID=1000"
            "GID=1000"
            "NIFI_VERSION=${{ env.NIFI_VERSION }}"
            "MIRROR_BASE_URL=https://archive.apache.org/dist"
            "BASE_URL=https://archive.apache.org/dist"
            "DISTRO_PATH=${{ env.NIFI_VERSION }}"
            "IMAGE_TAG=16-jdk-buster"
          tags: mkoppanen/nifi:${{ env.NIFI_VERSION }}-16-jdk